### ISSUE TITLE
Deploy and build the backend application failed.

### ISSUE THREAD

**Issue by v-minh1** [Azure-Samples/animal-rescue#6]
![image](https://user-images.githubusercontent.com/41893881/164414916-aa7f2899-b953-4107-b1f5-fe5573f89a0d.png)
[build-result--1.log](https://github.com/Azure-Samples/animal-rescue/files/8529224/build-result--1.log)
![image](https://user-images.githubusercontent.com/41893881/164414997-46ff5d6d-4fcc-458c-aacd-53d3eb477a60.png)

**Comment by qingc** [comment]
The issue is resolved after we clone this sample app repository on Linux Environment(using WSL). We should note in the doc that user should not clone the app repository on Windows or else will meet with this build error.

**Comment by maly7** [comment]
Thanks, @v-minh1 and @qingc for reporting this. I've added a `.gitattributes` file that ensures `lf` line endings for the `gradlew` shell script. This resolved the issue on my windows environment.
