### ISSUE TITLE
Register Application with Azure AD failed for aad application named with "animial-rescue" already existed

### ISSUE THREAD

**Issue by qingc** [Azure-Samples/animal-rescue#8]
![image](https://user-images.githubusercontent.com/11208278/165045954-2b005345-fb84-42fe-af7b-d2723ccd2232.png)
Met with this error in this [step](https://github.com/Azure-Samples/animal-rescue/blob/Azure/README.md#register-application-with-azure-ad). The reason is AAD app named with "animal-rescue" is already existed. We use another name for the AAD app and unblock this issue eventually.

**Comment by maly7** [comment]
Thanks, @qingc. Would these [updated instructions](https://github.com/Azure-Samples/animal-rescue/pull/10/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R383) prevent others from running into the same issue?

**Comment by qingc** [comment]
> Thanks, @qingc. Would these [updated instructions](https://github.com/Azure-Samples/animal-rescue/pull/10/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R383) prevent others from running into the same issue?

Yes, that's much better. Thank you! @maly7
